name: cd
on: push

# env:
#   DEPLOYMENT: blog
#   YAMLPATH: blog-mitchell/blog.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Build and push to Harbor
        uses: aevea/action-kaniko@master
        with:
          registry: harbor.mitchellscott.us
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASS }}
          build_file: ./Dockerfile
          image: library/send2remarkable
          tag: ${{ steps.slug.outputs.sha8 }}
          cache: false
          cache_registry: harbor.mitchellscott.us/library/cache
          extra_args: --cache-copy-layers

  # deploy:
  #   runs-on: ubuntu-latest
  #   name: Deploy to flux
  #   needs: build
  #   steps:
  #     - name: Check out Kubernetes repo
  #       uses: actions/checkout@v3
  #       with:
  #         repository: rmitchellscott/kubernetes-apps
  #         token: ${{ secrets.PAT }}
  #     - name: Get short SHA
  #       id: slug
  #       run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
  #     - name: Set up yq
  #       uses: frenck/action-setup-yq@v1
  #     - name: Replace the image tag
  #       env:
  #         TAG: ${{ steps.slug.outputs.sha8 }}
  #       run: yq -i e '(select(.kind=="Deployment" and .metadata.name==env(DEPLOYMENT)) | .spec.template.spec.containers.[].image) |= split(":").0 + ":" + env(TAG)' $YAMLPATH
  #     - name: Commit and push
  #       uses: stefanzweifel/git-auto-commit-action@v4
  #       with:
  #         commit_message: Update image tag for ${{env.DEPLOYMENT}} to ${{ steps.slug.outputs.sha8 }}